#!/bin/bash
# Dmitriy Litvin 2017

count=$(ping -c 2 -W 1 $1 | grep 'received' | awk -F',' '{print $2}' | awk '{print $1}')
if (( $count < 2)); then
echo Host $1 unreachable
exit 1; fi

port=`/usr/bin/snmpwalk -v 2c -c $2  $1 1.3.6.1.2.1.2.2.1.8.$3 |  cut -d":" -f2` 

if [ $port = 1 ]; then
echo Object is closed, port $3 UP
exit 0; fi

if [ $port = 2 -o $port = 7 ]; then
echo Object is open, port $3 DOWN
exit 2; fi

date >> /tmp/check_security.err.log
echo $count $port >> /tmp/check_security.err.log
echo $count $port
exit 1


