#!/bin/bash
# Dmitriy Litvin 2017

count=$(ping -c 2 -W 1 $1 | grep 'received' | awk -F',' '{print $2}' | awk '{print $1}')
echo $count
if (( $count < 2)); then
echo Host $1 unreachable
exit 1; fi



