#!/bin/sh
#Dmitriy Litvin 2014

cisco_cpu=`/usr/bin/snmpwalk -v 1 -O n -c $1 $2  .1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.4.0 | /usr/bin/cut -f 3 -d "(" | /usr/bin/cut -f1 -d "."`

cisco_temp=`/usr/bin/snmpwalk -v 1 -O n -c $1 $2 .1.3.6.1.4.1.674.10895.5000.2.6132.1.1.43.1.8.1.4 | /usr/bin/awk '{printf $4}'`

if [[ $cisco_cpu >  "35" ]]
then
echo PROBLEM, CPU Usage: $cisco_cpu %, Temp: $cisco_temp c
exit 1
#else
fi

if [[ $cisco_temp >  "30" ]]
then
echo PROBLEM, CPU Usage: $cisco_cpu %, Temp: $cisco_temp c
exit 1
#else
fi

echo CPU Usage: $cisco_cpu %, Temp: $cisco_temp c
exit 0
