#!/bin/bash
#Dmitriy Litvin 2017

count=$(ping -c 1 -W 1 $2 | grep 'received' | awk -F',' '{print $2}' | awk '{print $1}')
if (( $count < 1)); then
echo Host $2 unreachable
exit 2; fi

state_ups=`/usr/bin/snmpwalk -v 1 -O n -c $1 $2  1.3.6.1.2.1.33.1.4.1   | awk '{printf $4}'`
bat_ch=`/usr/bin/snmpwalk    -v 1 -O n -c $1 $2  1.3.6.1.2.1.33.1.2.4.0 | awk '{printf $4}'`
ups_temp=`/usr/bin/snmpwalk  -v 1 -O n -c $1 $2  1.3.6.1.2.1.33.1.2.7   | awk '{printf $4}'`

if [ "$state_ups" = "5" ]; then
echo On batteries, charge  $bat_ch %, Temp $ups_temp C
exit 1; fi

if (( $bat_ch < 15 ));then
echo  Low battery $bat_ch %, Temp $ups_temp C
exit 1; fi

if (( $ups_temp >  49 || $ups_temp <  10 )); then
echo Temperature warning $ups_temp C, charge  $bat_ch %
exit 1; fi

if [ "$state_ups" = "3" ]; then
echo Online, charge $bat_ch %, Temp $ups_temp C
exit 0; fi

if [ "$state_ups" = "2" ]; then
echo None, charge $bat_ch %, Temp $ups_temp C
exit 1; fi

if [ "$state_ups" = "4" ];then
echo Bypass, charge $bat_ch %, Temp $ups_temp C
exit 1; fi

if [ "$state_ups" = "6" ];then
echo Booster, charge $bat_ch %, Temp $ups_temp C
exit 1; fi

if [ "$state_ups" = "7" ];then
echo Reducer, charge $bat_ch %, Temp $ups_temp C
exit 1; fi

if [ "$bat_ch" = "0" ];then
echo Problem, charge $bat_ch %, Temp $ups_temp C
exit 1; fi

if [ "$state_ups" = "1" ];then
echo  Other?, charge $bat_ch %, Temp $ups_temp C
exit 0; fi

echo $2 SNMP error)
exit 2

