#!/bin/sh
switch=`/usr/bin/snmpwalk  -t 0.1  -v 2c -O n -c $1 $2 .1.3.6.1.2.1.1.1.0 | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 2`
if [ $switch =  ]
then echo Timeout No Response
exit 0
fi
if [ $switch = ZTE ]
then
echo $switch not supported.
exit 0
fi
if [ $switch = DGS-3100-24TG ]
then
echo $switch not supported.
exit 0
fi
if [ $switch = DGS-3610-26G ]
then
echo $switch not supported.
exit 0
fi
block=`/usr/bin/snmpwalk  -t 0.1  -v 2c -O n -c $1 $2 1.3.6.1.4.1.171.12.23.4.2.1.4 |   /usr/bin/cut  -d "D" -f 2 |  /usr/bin/cut -d ":" -f 2` 
blockc=`echo $block |  /usr/bin/wc -w`
if [ $blockc -lt  13 ]
then
echo $switch. blocked $blockc MAC.
exit 0
else
blockp=`echo $block | /usr/bin/cut -d " " -f 2`
echo $switch blocked $blockc MAC on port $blockp
exit 1
fi


